language: c
sudo: required
compiler:
  - gcc
  - clang
install:
  - sudo apt-get update -qq
  - sudo apt-get install gcc-multilib python-pip cmake
  - sudo pip install conan conan_package_tools
script:
  - python build.py
